name: iOS Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test using iPhone Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        working-directory: saint-of-the-day-ios
        env:
          platform: iOS Simulator
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          xcodebuild build-for-testing \
            -scheme SaintOfTheDay \
            -project SaintOfTheDay.xcodeproj \
            -destination "platform=$platform,name=$device" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Test
        working-directory: saint-of-the-day-ios
        env:
          platform: iOS Simulator
        run: |
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          xcodebuild test-without-building \
            -scheme SaintOfTheDay \
            -project SaintOfTheDay.xcodeproj \
            -destination "platform=$platform,name=$device"
